# Generated by Django 6.1 on 2026-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_squashed_new_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('PU', 'PUBLISH'), ('PR', 'PRIVATE')], default='DF', max_length=2),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(null=True),
        ),
    ]
