# Generated by Django 6.1 on 2026-09-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productmodel_state_alter_productmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Published'), ('PR', 'Private')], default='DF', max_length=2),
        ),
    ]
