# Generated by Django 6.1 on 2026-09-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_productmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-updated', '-timestamp')},
        ),
    ]
