from rest_framework import serializers

from ecommerce.models import (
    ProductModel,  # Import from ProductModel in ecommerce.models
)


class ProductSerializer(serializers.ModelSerializer):
    class Meta:
        model = ProductModel
        fields = (
            "id",
            "title",
            "description",
            "slug",
            "price",
            "seller",
            "color",
            "product_dimensions",
            "user",
        )
        read_only_fields = ("slug",)  # The slug is generated by a signal
